### PR TITLE
Add Portuguese Translation

### PR DESCRIPTION
**Pull request by LiveLM**
This pull request adds a Portuguese Translation into the launcher.
Should be adequate for both Brazilian Portuguese and European Portuguese, but @peachflavored, please tell me if you find anything unusual or weird.
[Spreadsheet with all the strings for easy viewing.](https://docs.google.com/spreadsheets/d/1_R2mcCnvDPz-R7DHj6sRQGM0jVfQolTpeMGjtYCrLr0/edit?usp=sharing)

### CODE REVIEW

**Comment by peachflavored** [comment]
All seems fine by me. I might need help with merging my translation with the official AM2R translations by creating a pull request since I'm new to this GitHub thing and can't seem to do it by myself.

**Comment by Miepee** [comment]
So, if I see this correctly, this was already proof-read by:
Live (brazilian)
Chico (brazilian)
Tally (brazilian)
PeachFlavored (portugal)

@peachflavored do you have connections to `Katherine_S2003`? Could you ask them if they could proof-read over it as well?
Otherwise looks good to me then, 

> I might need help with merging my translation with the official AM2R translations by creating a pull request since I'm new to this GitHub thing and can't seem to do it by myself.

A bit offtopic, but the way this works is:
- Fork the [AM2R-Localizations repo](https://github.com/AM2R-Community-Developers/AM2R-Localizations) (which you already seem to have done)
- Add your portguese.ini in there
- click on the "Pull Request" Tab, and then "Create new Pull Request"

**Comment by peachflavored** [comment]
@Miepee I already contacted her about this and I'm waiting for a response but I'm safe to say that the translation is good. Also thanks for helping me out with the Pull Request stuff.

**Comment by Lojemiru** [comment]
Cool, that's plenty of reviewers for me to feel safe merging this. Feel free to open issues or another PR should you notice anything that was missed :)

**Comment by peachflavored** [comment]
I've spoke to Katherine_S2003 and she agreed to have her username added to the list of proof-readers of my translation.

**Comment by Miepee** [comment]
> 
> 
> I've spoke to Katherine_S2003 and she agreed to have her username added to the list of proof-readers of my translation.

Wait, is this referring to this PR for the Launcher, or the other PR regarding AM2R-Portguguese?

**Comment by peachflavored** [comment]
@Miepee the PR referring to the European Translation for the game. I didn't spoke about the Launcher's translation since 4 people should be good enough being 3 of them Brazilians. :)

**Comment by Miepee** [comment]
Ah. Well, post PR comments then to their respective PR, makes it easier to keep track of.

**Pull request merged**
