### PR TITLE
Add Simplified Chinese localization

### PR DESCRIPTION
**Pull request by Ghost-J-R**
now you can choose Smplified Chinese in the launcher!

### CODE REVIEW

**Comment by Miepee** [comment]
Just wanted to give a heads up, and mention that a few strings have been edited.
`AutoUpdate` has been split up into `AutoUpdateAM2R` and `AutoUpdateLauncher`, `OpenProfileFolder` and `OpenProfileFolderToolTip` have been added, `ApkButtonEnabledToolTip` and `PlayButtonInstallToolTip` have been edited to use $NAME instead of a space, and the dangling newline of `ProfileNotes` as well as the dangling space of `ProgressbarProgress` have been removed.
Here are the y all along with their english counterpart:

```
ApkButtonEnabledToolTip	Create an APK for $NAME	
AutoUpdateAM2R	Automatically update AM2R	
AutoUpdateLauncher	Automatically update the AM2RLauncher	
OpenProfileFolder	OPEN PROFILE FOLDER	
OpenProfileFolderToolTip	Opens the folder where game files are located for $NAME.	
PlayButtonInstallToolTip	Install $NAME	
ProfileNotes	Profile notes:	
ProgressbarProgress	Progress:	
```

**Comment by Hambaka** [comment]
I talked to Ghost-J-R, he is currently on a business trip. But the problem is that he doesn't take his own laptop with him, so he can only update the translation in November. (after the business trip)

**Comment by Miepee** [comment]
That's fine, as we're still waiting for one more chinese person to look over this translation.

**Comment by Miepee** [comment]
Out of curiosity, might I ask why you closed the PR? Are you not interested anymore in adding a chinese translation?

**Comment by Ghost-J-R** [comment]
I will creat a new version that fixed the string




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月28日(星期天) 晚上8:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [AM2R-Community-Developers/AM2RLauncher] Add Simplified Chinese localization (#20)





 
Out of curiosity, might I ask why you closed the PR? Are you not interested anymore in adding a chinese translation?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Miepee** [comment]
I see. For the future, creating a new PR for that isn't necessary. You can just add a new commit to your branch.

**Comment by Ghost-J-R** [comment]
ok,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月28日(星期天) 晚上8:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [AM2R-Community-Developers/AM2RLauncher] Add Simplified Chinese localization (#20)





 
I see. For the future, creating a new PR for that isn't necessary. You can just add a new commit to your branch.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
